import React, { useState } from 'react';
import { 
  FileText, 
  RefreshCw, 
  Edit, 
  Download,
  GitBranch,
  Clock,
  Sparkles,
  Plus,
  Github,
  Zap
} from 'lucide-react';
import { Card, CardContent, CardHeader } from '../ui/Card';
import { Button } from '../ui/Button';
import { RepositoryConnector } from '../repository/RepositoryConnector';
import { DocGenerator } from './DocGenerator';
import { useAppStore } from '../../stores/useAppStore';
import { GeneratedDocumentation } from '../../services/docGenerator';
import { RepositoryAnalysis } from '../../types/github';

const mockDocs = [
  {
    id: '1',
    title: 'API Documentation',
    description: 'Complete API reference and integration guide',
    lastUpdated: new Date('2024-01-15'),
    autoGenerated: true,
    status: 'current',
  },
  {
    id: '2',
    title: 'Architecture Overview',
    description: 'System architecture and design patterns',
    lastUpdated: new Date('2024-01-14'),
    autoGenerated: true,
    status: 'current',
  },
  {
    id: '3',
    title: 'Component Library',
    description: 'React components documentation',
    lastUpdated: new Date('2024-01-13'),
    autoGenerated: false,
    status: 'outdated',
  },
  {
    id: '4',
    title: 'Database Schema',
    description: 'Complete database structure and relationships',
    lastUpdated: new Date('2024-01-12'),
    autoGenerated: true,
    status: 'current',
  },
];

export const DocsView: React.FC = () => {
  const { repositories, currentRepository } = useAppStore();
  const [generating, setGenerating] = useState(false);
  const [showConnector, setShowConnector] = useState(false);
  const [selectedRepo, setSelectedRepo] = useState<string | null>(null);
  const [generatedDocs, setGeneratedDocs] = useState<Map<string, GeneratedDocumentation>>(new Map());

  const handleGenerateDocs = async () => {
    setGenerating(true);
    // Simulate AI documentation generation
    await new Promise(resolve => setTimeout(resolve, 3000));
    setGenerating(false);
  };

  const handleDocumentationGenerated = (repoId: string, documentation: GeneratedDocumentation) => {
    setGeneratedDocs(prev => new Map(prev.set(repoId, documentation)));
  };

  const getRepositoryAnalysis = (repoId: string): RepositoryAnalysis | null => {
    // In a real implementation, this would fetch the analysis from the store or API
    // For now, we'll create a mock analysis
    const repo = repositories.find(r => r.id === repoId);
    if (!repo) return null;

    return {
      repository: {
        id: parseInt(repo.id),
        name: repo.name,
        full_name: repo.name,
        description: repo.description,
        html_url: repo.url,
        clone_url: repo.url,
        language: repo.language,
        stargazers_count: repo.stars,
        forks_count: 0,
        open_issues_count: 0,
        default_branch: 'main',
        created_at: new Date().toISOString(),
        updated_at: repo.lastUpdated.toISOString(),
        pushed_at: repo.lastUpdated.toISOString(),
        size: 1000,
        owner: {
          login: 'owner',
          avatar_url: '',
          html_url: '',
        },
      },
      structure: [],
      contributors: [],
      languages: { [repo.language]: 1000 },
      recentCommits: [],
      summary: {
        totalFiles: 50,
        totalLines: 5000,
        primaryLanguage: repo.language,
        lastActivity: repo.lastUpdated.toISOString(),
        commitFrequency: 10,
      },
    };
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-white mb-2">Living Documentation</h1>
          <p className="text-dark-400">AI-generated and maintained codebase documentation</p>
        </div>
        <div className="flex items-center space-x-3">
          <Button variant="ghost" onClick={() => setShowConnector(true)}>
            <Plus size={16} className="mr-2" />
            Connect Repository
          </Button>
          <Button variant="ghost">
            <Download size={16} className="mr-2" />
            Export
          </Button>
          <Button
            onClick={handleGenerateDocs}
            loading={generating}
          >
            <Sparkles size={16} className="mr-2" />
            Generate with AI
          </Button>
        </div>
      </div>

      {/* Repository Selector */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <h3 className="text-lg font-semibold text-white">Connected Repositories</h3>
            <div className="flex items-center space-x-2">
              <GitBranch size={16} className="text-dark-400" />
              <span className="text-sm text-dark-400">main branch</span>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          {repositories.length > 0 ? (
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {repositories.map((repo) => {
                const hasGeneratedDocs = generatedDocs.has(repo.id);
                const isSelected = selectedRepo === repo.id;
                
                return (
                  <div
                    key={repo.id}
                    className={`p-4 border rounded-lg transition-colors cursor-pointer ${
                      isSelected 
                        ? 'border-primary-500 bg-primary-900/20' 
                        : 'border-dark-600 hover:border-primary-500'
                    }`}
                    onClick={() => setSelectedRepo(isSelected ? null : repo.id)}
                  >
                    <div className="flex items-start space-x-3 mb-3">
                      <div className="w-8 h-8 bg-dark-700 rounded-lg flex items-center justify-center">
                        <Github size={16} className="text-primary-400" />
                      </div>
                      <div className="flex-1">
                        <h4 className="font-medium text-white mb-1">{repo.name}</h4>
                        <p className="text-sm text-dark-400 mb-2">{repo.description}</p>
                      </div>
                      {hasGeneratedDocs && (
                        <div className="w-3 h-3 bg-success-400 rounded-full" title="Documentation generated" />
                      )}
                    </div>
                    
                    <div className="flex items-center justify-between text-xs">
                      <div className="flex items-center space-x-3">
                        <span className="text-dark-500">{repo.language}</span>
                        <span className="text-dark-500">⭐ {repo.stars}</span>
                      </div>
                      {isSelected && (
                        <div className="flex items-center space-x-1 text-primary-400">
                          <Zap size={12} />
                          <span>Selected</span>
                        </div>
                      )}
                    </div>

                    {repo.structure && (
                      <div className="mt-3 pt-3 border-t border-dark-700">
                        <div className="flex items-center justify-between text-xs text-dark-500">
                          <span>{repo.structure.modules.length} modules</span>
                          <span>{repo.structure.services.length} services</span>
                        </div>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          ) : (
            <div className="text-center py-8">
              <div className="w-16 h-16 bg-dark-700 rounded-full flex items-center justify-center mx-auto mb-4">
                <Github className="w-8 h-8 text-dark-400" />
              </div>
              <h4 className="text-lg font-medium text-white mb-2">No Repositories Connected</h4>
              <p className="text-dark-400 mb-4">
                Connect your GitHub repositories to start generating documentation
              </p>
              <Button onClick={() => setShowConnector(true)}>
                <Plus size={16} className="mr-2" />
                Connect Repository
              </Button>
            </div>
          )}
        </CardContent>
      </Card>

      {/* AI Documentation Generator */}
      {selectedRepo && (
        <div className="space-y-6">
          {(() => {
            const repo = repositories.find(r => r.id === selectedRepo);
            const analysis = getRepositoryAnalysis(selectedRepo);
            
            if (!repo || !analysis) return null;
            
            return (
              <DocGenerator
                repository={repo}
                analysis={analysis}
                onDocumentationGenerated={(doc) => handleDocumentationGenerated(repo.id, doc)}
              />
            );
          })()}
        </div>
      )}

      {/* Existing Documentation Grid */}
      {repositories.length > 0 && !selectedRepo && (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {mockDocs.map((doc) => (
            <Card key={doc.id} hover>
              <CardHeader>
                <div className="flex items-start justify-between">
                  <div className="flex items-start space-x-3">
                    <div className="w-10 h-10 bg-dark-700 rounded-lg flex items-center justify-center">
                      <FileText size={20} className="text-primary-400" />
                    </div>
                    <div>
                      <h3 className="font-semibold text-white">{doc.title}</h3>
                      <p className="text-sm text-dark-400 mt-1">{doc.description}</p>
                    </div>
                  </div>
                  <div className="flex items-center space-x-2">
                    {doc.autoGenerated && (
                      <div className="flex items-center space-x-1 text-xs text-secondary-400 bg-secondary-900/20 px-2 py-1 rounded">
                        <Sparkles size={12} />
                        <span>AI</span>
                      </div>
                    )}
                    <div
                      className={`w-3 h-3 rounded-full ${
                        doc.status === 'current' ? 'bg-success-400' : 'bg-warning-400'
                      }`}
                    />
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-4 text-sm text-dark-400">
                    <div className="flex items-center space-x-1">
                      <Clock size={14} />
                      <span>Updated {doc.lastUpdated.toLocaleDateString()}</span>
                    </div>
                  </div>
                  <div className="flex items-center space-x-2">
                    <Button variant="ghost" size="sm">
                      <Edit size={14} className="mr-1" />
                      Edit
                    </Button>
                    <Button variant="ghost" size="sm">
                      <RefreshCw size={14} className="mr-1" />
                      Refresh
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {/* AI Generation Status */}
      {generating && (
        <Card>
          <CardContent className="p-6">
            <div className="flex items-center space-x-4">
              <div className="w-8 h-8 bg-primary-600 rounded-lg flex items-center justify-center animate-pulse">
                <Sparkles className="w-4 h-4 text-white" />
              </div>
              <div>
                <h4 className="font-medium text-white">Generating Documentation</h4>
                <p className="text-sm text-dark-400">AI is analyzing your codebase and creating comprehensive docs...</p>
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Repository Connector Modal */}
      <RepositoryConnector
        isOpen={showConnector}
        onClose={() => setShowConnector(false)}
      />
    </div>
  );
};